# Generated by Django 2.2.16 on 2020-09-03 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_registry',
            new_name='registry_date',
        ),
        migrations.AddField(
            model_name='account',
            name='registry_sent',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Письмо о регистрации отправлено'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
