# Generated by Django 2.2.16 on 2020-09-08 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20200903_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название темы/вебинара')),
                ('date_start', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата старта марафона')),
                ('date_create', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий/Описание')),
            ],
            options={
                'verbose_name': 'Марафон',
                'verbose_name_plural': 'Марафон',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Адрес сайта')),
                ('contact_phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='Контактный телефон')),
                ('contact_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный Email')),
                ('soc_igm', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('soc_vk', models.URLField(blank=True, null=True, verbose_name='Ссылка на Вконтакте')),
                ('soc_fb', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('metadescr', models.TextField(blank=True, default='', null=True, verbose_name='Meta Description')),
                ('metakeywords', models.TextField(blank=True, default='', null=True, verbose_name='Meta Keyword')),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='registry_date',
        ),
        migrations.AddField(
            model_name='account',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Статус подтверждения аккаунта (совершен вход в ЛК)'),
        ),
        migrations.AddField(
            model_name='account',
            name='date_registry',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Порядковый номер темы в марафоне')),
                ('title', models.CharField(max_length=250, verbose_name='Название темы/вебинара')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий к теме/вебинару')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Стоимость темы (в рублях)')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_publish', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 14, 50, 18, 717029), null=True, verbose_name='Дата публикации')),
                ('marathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Marathon', verbose_name='Марафон')),
            ],
            options={
                'verbose_name': 'Тема/Вебинар',
                'verbose_name_plural': 'Темы/Вебинары',
                'unique_together': {('number', 'marathon')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания отзыва')),
                ('custom_user', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('custom_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('custom_photo', models.FileField(blank=True, upload_to='images/avatars/', verbose_name='Аватар')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Account', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='marathone',
            field=models.ManyToManyField(blank=True, to='front.Marathon', verbose_name='Марафоны'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Порядковый номер видео (номер отображения в уроке)')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка на YouTube видео')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий к видео')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_publish', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 14, 50, 18, 717742), null=True, verbose_name='Дата публикации')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Lesson', verbose_name='Тема/Вебинар')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'unique_together': {('number', 'lesson')},
            },
        ),
    ]
