# Generated by Django 2.2.16 on 2020-09-08 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200908_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус подтверждения аккаунта (совершен вход в ЛК)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 15, 49, 47, 157680), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 15, 49, 47, 158226), null=True, verbose_name='Дата публикации'),
        ),
    ]
