# Generated by Django 2.2.16 on 2020-09-10 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20200908_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='promo',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на YouTube-видео (Промо-ролик)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 10, 12, 21, 44, 926402), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 10, 12, 21, 44, 926943), null=True, verbose_name='Дата публикации'),
        ),
    ]
