# Generated by Django 2.2.16 on 2020-09-10 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20200910_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 10, 12, 36, 21, 844680), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='date_create',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 10, 12, 36, 21, 845191), null=True, verbose_name='Дата публикации'),
        ),
    ]
