# Generated by Django 2.2.16 on 2020-09-10 10:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20200910_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 10, 17, 13, 1, 550360), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Порядковый номер темы в марафоне'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 10, 17, 13, 1, 550879), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Порядковый номер видео (номер отображения в уроке)'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuid', models.CharField(blank=True, max_length=250, null=True, verbose_name='Идентификатор платежа в ЯК')),
                ('date_pay', models.DateTimeField(auto_now=True, verbose_name='Дата оплаты')),
                ('date_approve', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата подтверждения платежа')),
                ('status', models.CharField(blank=True, max_length=250, null=True, verbose_name='Статус платежа в ЯК')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Запрос в ЯК')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ от ЯК')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='front.Account', verbose_name='Аккаунт')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='front.Lesson', verbose_name='Тема/Вебинар')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платёжи',
            },
        ),
    ]
