# Generated by Django 2.2.16 on 2020-09-10 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20200910_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 10, 17, 15, 5, 305944), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 10, 17, 15, 5, 306481), null=True, verbose_name='Дата публикации'),
        ),
    ]
