# Generated by Django 2.2.16 on 2020-09-11 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_auto_20200910_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 15, 30, 12, 522866), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_approve',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения платежа'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 15, 30, 12, 523474), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ID видео на YouTube'),
        ),
    ]
