# Generated by Django 2.2.16 on 2020-09-16 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20200911_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип отзыва')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 9, 11, 0, 377886), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 9, 11, 0, 378697), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='kind',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.ReviewKind', verbose_name='Тип отзыва'),
        ),
    ]
