# Generated by Django 2.2.16 on 2020-09-18 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_auto_20200917_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 18, 10, 13, 38, 316009, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('6d8886de-53cd-4e0a-bc1f-aaf927ae9a73'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 18, 10, 13, 38, 316532, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
    ]
