# Generated by Django 2.2.16 on 2020-09-22 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_auto_20200918_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.FilePathField(blank=True, null=True, path='/tmp/marathon_remote/media', verbose_name='Квитанция'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 9, 0, 54, 140959, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='confirmation_token'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('466641af-c5cd-4fa9-ab91-0581f9b15d70'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 9, 0, 54, 141701, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
    ]
