# Generated by Django 2.2.16 on 2020-09-23 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_auto_20200922_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status_mail_lesson',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Напоминание в день урока отправлено'),
        ),
        migrations.AddField(
            model_name='uppersetting',
            name='shopid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID магазина в ЯК'),
        ),
        migrations.AddField(
            model_name='uppersetting',
            name='shopid_test',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID тестового магазина в ЯК'),
        ),
        migrations.AddField(
            model_name='uppersetting',
            name='test_mode',
            field=models.BooleanField(default=False, verbose_name='Тестовый режим ЯК'),
        ),
        migrations.AddField(
            model_name='uppersetting',
            name='yandex_api_key',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='yandex_api_key'),
        ),
        migrations.AddField(
            model_name='uppersetting',
            name='yandex_api_key_test',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='yandex_api_key_test'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('f16a6ac9-08b3-42a5-ba32-ded2b1101360'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
