# Generated by Django 2.2.16 on 2020-09-23 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_auto_20200923_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='uppersetting',
            name='return_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='return_url для ЯК'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ca80f6a8-b57e-47e0-8e46-26b346dba2c5'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
