# Generated by Django 2.2.16 on 2020-09-24 09:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_auto_20200923_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_publish',
        ),
        migrations.AddField(
            model_name='lesson',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Тема доступна без покупки марафона'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость марафона (в рублях)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='marathon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='front.Marathon', verbose_name='Марафон'),
        ),
        migrations.AddField(
            model_name='setting',
            name='fake_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость марафона (в рублях) до скидки'),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='promo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на YouTube-видео (Промо-ролик)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('60e84655-8d3d-41b8-9596-adef6ff65e40'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
