# Generated by Django 2.2.16 on 2020-09-28 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0028_auto_20200928_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['number'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('6fc91bc6-c169-47e9-99e7-89785b5a2348'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
