# Generated by Django 2.2.16 on 2020-09-29 10:01

from django.db import migrations, models
import front.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0030_auto_20200929_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status_mail_lesson',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='hometask_file',
            field=models.FileField(blank=True, null=True, upload_to=front.models.user_directory_path, verbose_name='Файл Домашнего задания по теме/вебинару'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c46f591c-a3f9-4494-8a1f-2684d9466dc6'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
