# Generated by Django 2.2.16 on 2020-09-29 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0031_auto_20200929_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='marathone',
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('1c1eae6d-1ea4-4338-b809-2662b10b949e'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
