# Generated by Django 2.2.16 on 2020-09-30 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0032_auto_20200929_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mail_lesson_not_recieve',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Напоминание не получили'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status_mail_lesson',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Напоминание в день урока отправлено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('f8353f42-6df9-48ef-a545-5e5514ad3ff5'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
