# Generated by Django 2.2.16 on 2020-10-02 05:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0034_auto_20200930_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e4a70eeb-8875-41d1-942c-3f228dfba57e'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата рассылки')),
                ('recipient', models.SmallIntegerField(choices=[(1, 'Оплатившие'), (2, 'Не оплатившие'), (3, 'Все')], verbose_name='Получатели')),
                ('subject', models.TextField(default='', verbose_name='Тема письма')),
                ('message', models.TextField(default='', verbose_name='Сообщение')),
                ('attach', models.FileField(upload_to='', verbose_name='Вложение')),
                ('marathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Marathon', verbose_name='Марафон')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
