# Generated by Django 2.2.16 on 2020-10-02 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0035_auto_20201002_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата действия')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Действие')),
                ('input_data', models.TextField(blank=True, null=True, verbose_name='Данные на входе')),
                ('output_data', models.TextField(blank=True, null=True, verbose_name='Данные на выходе')),
                ('result', models.SmallIntegerField(choices=[(0, 'Создано'), (1, 'Успешно'), (2, 'Ошибка')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='mailing',
            name='attach',
            field=models.FileField(blank=True, upload_to='', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipient',
            field=models.SmallIntegerField(choices=[(1, 'Оплатившие'), (2, 'Не оплатившие'), (3, 'Все')], default=3, verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='subject',
            field=models.CharField(default='', max_length=250, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('a832f04c-f109-42fe-8263-abe1ad0e2799'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
