# Generated by Django 2.2.16 on 2020-10-13 04:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0036_auto_20201002_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='kind',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.ReviewKind', verbose_name='Тип отзыва'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Подэтапы, описание, пункты темы через запятую'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0e2ea63d-022f-48fb-93ee-9aa32ae76f89'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
    ]
