# Generated by Django 2.2.16 on 2020-10-15 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0038_auto_20201014_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_registry',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='logging',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата действия'),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_pay',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('b1b931d8-efca-47a9-b7a5-d49f399b2309'), primary_key=True, serialize=False, verbose_name='Идентификатор платежа в системе / Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
