# Generated by Django 2.2.16 on 2020-10-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0040_auto_20201015_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ID видео на YouTube (устаревшее)'),
        ),
    ]
