# Generated by Django 2.2.16 on 2020-10-21 07:42

from django.db import migrations, models
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0041_auto_20201021_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to=front.models.video_directory_path, verbose_name='Видеофайл, .mp4'),
        ),
    ]
