# Generated by Django 2.2.16 on 2020-10-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0042_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название марафона'),
        ),
    ]
