# Generated by Django 2.2.16 on 2020-10-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0043_auto_20201025_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='advantages',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Достоинства (на Главной)'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='subtitle',
            field=models.CharField(default='', max_length=250, verbose_name='Подзаголовок (на Главной)'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='promo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на YouTube-видео (Промо-ролик на Главной)'),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название марафона (на Главной)'),
        ),
    ]
