# Generated by Django 2.2.16 on 2020-10-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0044_auto_20201026_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='images/gifts/', verbose_name='Картинка на сайте')),
            ],
            options={
                'verbose_name': 'Бонусы и Подарки марафонов',
                'verbose_name_plural': 'Бонусы и Подарки марафонов',
            },
        ),
        migrations.AddField(
            model_name='marathon',
            name='outdated',
            field=models.BooleanField(default=False, verbose_name='Скрыть марафон с сайта'),
        ),
        migrations.AddField(
            model_name='setting',
            name='instruction',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Руководство администратора'),
        ),
        migrations.CreateModel(
            name='GiftItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Иконка fa-awesome')),
                ('advantage', models.CharField(max_length=255, verbose_name='Подпункт')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Gift', verbose_name='Бонус марафона')),
            ],
            options={
                'verbose_name': 'Подпункты Бонусов и Подарков марафонов',
                'verbose_name_plural': 'Подпункты Бонусов и Подарков марафонов',
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='marathon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='front.Marathon', verbose_name='Марафон'),
        ),
    ]
