# Generated by Django 2.2.16 on 2020-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0045_auto_20201027_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Подарки и Бонусы марафонов', 'verbose_name_plural': 'Подарки и Бонусы марафонов'},
        ),
        migrations.AlterModelOptions(
            name='giftitems',
            options={'verbose_name': 'Подпункты Подарков и Бонусов марафонов', 'verbose_name_plural': 'Подпункты Подарков и Бонусов марафонов'},
        ),
        migrations.AlterField(
            model_name='giftitems',
            name='icon',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Иконка fa-awesome'),
        ),
    ]
