# Generated by Django 2.2.16 on 2020-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0046_auto_20201027_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftitems',
            options={'ordering': ['number'], 'verbose_name': 'Подпункты Подарков и Бонусов марафонов', 'verbose_name_plural': 'Подпункты Подарков и Бонусов марафонов'},
        ),
        migrations.AddField(
            model_name='giftitems',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер отображения на сайте'),
            preserve_default=False,
        )
    ]
