# Generated by Django 2.2.16 on 2020-10-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0048_set_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='giftitems',
            unique_together={('number', 'gift')},
        ),
    ]
