# Generated by Django 2.2.16 on 2020-10-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0049_auto_20201027_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Опубликовать отзыв '),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='custom_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город (при ручном добавлении)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='custom_photo',
            field=models.FileField(blank=True, upload_to='images/avatars/', verbose_name='Аватар при ручном добавлении'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='custom_user',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя (при ручном добавлении)'),
        ),
        migrations.AlterField(
            model_name='giftitems',
            name='icon',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Иконка fa-awesome c сайта https://fontawesome.com/v4.7.0/icons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Подэтапы, описание, пункты темы в столбик'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активна (осуществить рассылку)'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='attach',
            field=models.FileField(blank=True, upload_to='', verbose_name='Вложение письма'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.TextField(default='', verbose_name='Сообщение письма'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный Email на сайте'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Контактный телефон на сайта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instruction',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Документация на сайт'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='main_marathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='front.Marathon', verbose_name='Марафон на главной странице сайта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soc_igm',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram на сайте'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soc_tm',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram на сайте'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soc_wa',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp на сайте'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ID видео на YouTube'),
        ),
    ]
