# Generated by Django 2.2.16 on 2020-10-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0050_auto_20201028_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='fake_cost',
            field=models.PositiveIntegerField(blank=True, default=2500, verbose_name='Стоимость марафона (в рублях) до скидки'),
        ),
    ]
