# Generated by Django 2.2.16 on 2020-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0053_auto_20201113_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppersetting',
            name='remote_video_dir',
            field=models.CharField(blank=True, default='/media/marathon/marathon/', max_length=100, verbose_name='Путь к папке с видеофайлами'),
        ),
    ]
