# Generated by Django 2.2.16 on 2020-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0054_auto_20201113_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/gifts/', verbose_name='Файл для отправки в письме (книга)'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing',
            field=models.BooleanField(default=False, verbose_name='В обработке'),
        ),
    ]
