# Generated by Django 2.2.16 on 2020-12-10 08:26

from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    Video = apps.get_model('front', 'Video')
    Video.objects.filter(url__isnull=True).update(url='')


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0057_auto_20201204_1144'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, migrations.RunPython.noop),
    ]
