# Generated by Django 2.2.16 on 2020-12-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0059_auto_20201210_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_pwd_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID для генерации сброса пароля'),
        ),
    ]
