# Generated by Django 2.2.16 on 2021-01-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0060_account_reset_pwd_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='fake_cost',
            field=models.PositiveIntegerField(blank=True, default=2500, null=True, verbose_name='Стоимость марафона (в рублях) до скидки'),
        ),
    ]
